### ISSUE TITLE
Error Using Nexus repository

### ISSUE THREAD

**Issue by reinaldo-pinto** [KilianB/JImageHash#31]
Hi, we are with the error below:

[ERROR] Failed to execute goal on project images: Could not resolve dependencies for project br.com.mobiauto:images:jar:0.0.2-SNAPSHOT: Failure to find com.github.kilianB:JImageHash:jar:3.0.0 in https://nexus.internal.com.br/repository/maven-group/ was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

- We configure in Nexus a Repo Proxy (error):
URL https://dl.bintray.com/kilianb/maven 
- We tried to configure Maven-central with the same repo (above). (error)

Our Nexus this makes the download of others dependencies (ok).

Help me???

**Comment by KilianB** [comment]
Sadly I do not have experience working with nexus, therefore I can't exactly pinpoint your issue.

It is expected that you are not able to resolve the artifact via maven central simply due to the fact that it is not published there. The code got released to JCenter which is a mirror and superset of maven central 

`````
<repositories>
	<repository>
		<id>jcenter</id>
		<url>https://jcenter.bintray.com/</url>
	</repository>
</repositories>
`````

If you take a look at https://dl.bintray.com/kilianb/maven/com/github/kilianB/ you can see that the code is available. In my opinion this is somehow related to your nexus configuration. 

Please also take a look at https://jfrog.com/knowledge-base/using-bintray-with-nexus/

Sorry that I can't provide any further help

**Comment by reinaldo-pinto** [comment]
Hi Killian, thank you. 
Through some of their information, we were able to solve.  (Resolved)

Let's share:
- Nexus - Add new proxy repository with name "jcenter":
![captura de tela 2019-02-19 as 11 41 19](https://user-images.githubusercontent.com/19714414/53023407-ed45cc00-343b-11e9-85bd-812193a284e7.png)

- Nexus - Add url bellow in proxy (remote storage):
https://dl.bintray.com/kilianb/maven/com/github/kilianB/

- Nexus - Add the new repo "jcenter" in maven-group:
![captura de tela 2019-02-19 as 11 49 44](https://user-images.githubusercontent.com/19714414/53023707-807f0180-343c-11e9-9bc7-58eeac938dae.png)

- pom.xml - On configuration file:
```
<repositories>
       <repository>
             <id>maven-group</id>
             <url>https://nexus.internal.com.br/repository/maven-group/</url>
       </repository>
</repositories>
```

Thank you very much.
